### ISSUE TITLE
does it work in laravel 5.6?

### ISSUE THREAD

**Issue by ghost** [kiberzauras/laravel.multilanguage#5]
Hi
does it work in laravel 5.6 version?
I have used it in my code with laravel 5.6 and everything is good but when I use url('example/example') or URL::to('example/example') in my blade page this error shows for me:

```
ErrorException (E_ERROR)
Method Kiberzauras\MultiLanguage\UrlGenerator::getScheme does not exist.
```

**Comment by grinry** [comment]
Hi,
unfortunately not. You should use [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization)

**Comment by ghost** [comment]
What a pity
